-- =====================================================
-- EXTENSIONS
-- =====================================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
 
-- =====================================================
-- CUSTOM TYPE (SQL Server table-type replacement)
-- =====================================================
CREATE TYPE item_list AS (
    product_id INT,
    quantity   INT
);
 
-- =====================================================
-- TABLES
-- =====================================================
 
CREATE TABLE account (
    account_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_code VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    roles VARCHAR(20) NOT NULL,
    CONSTRAINT ck_account_role CHECK (roles IN ('client', 'admin'))
);
 
CREATE TABLE admin (
    admin_id INT PRIMARY KEY,
    account_id INT,
    CONSTRAINT fk_account_admin
        FOREIGN KEY (account_id)
        REFERENCES account(account_id)
);
 
CREATE TABLE brands (
    brand_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_code VARCHAR(100) NOT NULL UNIQUE,
    brand_name TEXT NOT NULL
);
 
CREATE TABLE categories (
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT NOT NULL,
    category_code VARCHAR(100) NOT NULL UNIQUE
);
 
CREATE TABLE discount (
    discount_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount_name TEXT,
    discount_value NUMERIC(5,4),
    date_start TIMESTAMPTZ NOT NULL DEFAULT now(),
    date_end TIMESTAMPTZ NOT NULL DEFAULT now(),
    discount_code VARCHAR(100),
    CONSTRAINT ck_discount_value CHECK (discount_value BETWEEN 0 AND 1)
);
 
CREATE TABLE client (
    client_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INT NOT NULL,
    client_code VARCHAR(100) NOT NULL UNIQUE,
    client_name TEXT NOT NULL,
    total_money NUMERIC(18,2) NOT NULL CHECK (total_money >= 0),
    discount_id INT,
    CONSTRAINT fk_client_account
        FOREIGN KEY (account_id)
        REFERENCES account(account_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_client_discount
        FOREIGN KEY (discount_id)
        REFERENCES discount(discount_id)
        ON DELETE SET NULL
);
 
CREATE TABLE products (
    product_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(100) NOT NULL UNIQUE,
    product_name TEXT NOT NULL,
    price NUMERIC(18,2) NOT NULL CHECK (price > 0),
    descriptions TEXT,
    brand_id INT NOT NULL,
    category_id INT NOT NULL,
    stock INT NOT NULL DEFAULT 0 CHECK (stock >= 0),
    rating NUMERIC(3,1) CHECK (rating BETWEEN 0 AND 5),
    create_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    update_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    discount_id INT,
    CONSTRAINT fk_products_brand
        FOREIGN KEY (brand_id) REFERENCES brands(brand_id),
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories(category_id),
    CONSTRAINT fk_products_discount
        FOREIGN KEY (discount_id)
        REFERENCES discount(discount_id)
        ON DELETE SET NULL
);
 
CREATE TABLE cart (
    cart_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INT NOT NULL UNIQUE,
    CONSTRAINT fk_cart_client
        FOREIGN KEY (client_id)
        REFERENCES client(client_id)
        ON DELETE CASCADE
);
 
CREATE TABLE cart_item (
    cart_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    price NUMERIC(18,2) NOT NULL CHECK (price > 0),
    total_price NUMERIC(18,2)
        GENERATED ALWAYS AS (price * quantity) STORED,
    CONSTRAINT fk_cartitem_cart
        FOREIGN KEY (cart_id)
        REFERENCES cart(cart_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_cartitem_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);
 
CREATE TABLE orders (
    order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code VARCHAR(100) NOT NULL UNIQUE,
    client_id INT NOT NULL,
    total_price NUMERIC(18,2) NOT NULL CHECK (total_price > 0),
    statusorders TEXT NOT NULL
        CHECK (statusorders IN ('cancelled','completed','shipping','processing','pending','preparing')),
    create_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    address TEXT,
    phone_number VARCHAR(255),
    discount_id INT,
    final_price NUMERIC(18,2),
    CONSTRAINT fk_orders_client
        FOREIGN KEY (client_id)
        REFERENCES client(client_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_orders_discount
        FOREIGN KEY (discount_id)
        REFERENCES discount(discount_id)
        ON DELETE SET NULL
);
 
CREATE TABLE order_items (
    order_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    price NUMERIC(18,2) NOT NULL CHECK (price > 0),
    total_price NUMERIC(18,2)
        GENERATED ALWAYS AS (price * quantity) STORED,
    price_alterdiscount NUMERIC(18,2),
    CONSTRAINT fk_orderitems_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_orderitems_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);
 
CREATE TABLE product_images (
    image_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT NOT NULL,
    image_url VARCHAR(1000) NOT NULL,
    sortorder INT NOT NULL DEFAULT 1,
    CONSTRAINT fk_productimages_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);
 
CREATE TABLE product_specs (
    spec_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT NOT NULL,
    spec_key VARCHAR(100) NOT NULL,
    spec_value VARCHAR(100) NOT NULL,
    CONSTRAINT uq_productspec UNIQUE (product_id, spec_key),
    CONSTRAINT fk_productspec_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);
 
CREATE TABLE guarantee (
    guarantee_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT NOT NULL,
    date_start TIMESTAMPTZ NOT NULL DEFAULT now(),
    date_end TIMESTAMPTZ NOT NULL DEFAULT now(),
    guarantee_code VARCHAR(100),
    CONSTRAINT fk_guarantee_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);
 
-- =====================================================
-- STORED PROCEDURE -> FUNCTION
-- =====================================================
 
CREATE OR REPLACE FUNCTION create_order_with_items(
    p_client_id INT,
    p_address TEXT,
    p_phone TEXT,
    p_items item_list[]
)
RETURNS TABLE(order_id INT, order_code TEXT)
LANGUAGE plpgsql
AS $$
DECLARE
    v_order_id INT;
    v_order_code TEXT;
BEGIN
    IF EXISTS (
        SELECT 1
        FROM unnest(p_items) i
        LEFT JOIN products p ON p.product_id = i.product_id
        WHERE p.product_id IS NULL
    ) THEN
        RAISE EXCEPTION 'Product is null';
    END IF;
 
    v_order_code :=
        'ORD-' ||
        to_char(now(), 'YYYYMMDD-HH24MISS') || '-' ||
        substr(md5(random()::text), 1, 4);
 
    INSERT INTO orders (
        client_id, order_code, total_price,
        address, phone_number, statusorders, create_at
    )
    VALUES (
        p_client_id,
        v_order_code,
        1,
        p_address,
        p_phone,
        'preparing',
        now()
    )
    RETURNING order_id INTO v_order_id;
 
    INSERT INTO order_items (order_id, product_id, quantity, price)
    SELECT
        v_order_id,
        i.product_id,
        i.quantity,
        p.price
    FROM unnest(p_items) i
    JOIN products p ON p.product_id = i.product_id;
 
    UPDATE orders
    SET total_price = (
        SELECT SUM(total_price)
        FROM order_items
        WHERE order_id = v_order_id
    )
    WHERE order_id = v_order_id;
 
    RETURN QUERY
    SELECT v_order_id, v_order_code;
END;
$$;

INSERT INTO product_images (product_id, image_url, sortorder) VALUES
(1, 'https://laptops.vn/wp-content/uploads/2024/10/Dell-XPS-13-9350-2025-LAPTOPS.VN-1-2.jpg', 1),
(1, 'https://laptops.vn/wp-content/uploads/2024/10/Dell-XPS-13-9350-2025-LAPTOPS.VN-1-2.jpg', 2),
 
(2, 'https://www.notebookcheck.net/fileadmin/Notebooks/News/_nc4/Dell-XPS-13-9340-laptop.JPG', 1),
 
(3, 'https://th.bing.com/th/id/OIP.GTA_FRgDIEgpIm6_iszquQHaFK?w=283&h=197&c=7&r=0&o=7&dpr=1.1&pid=1.7&rm=3', 1),
 
(4, 'https://laptops.vn/wp-content/uploads/2024/10/Dell-XPS-13-9350-2025-LAPTOPS.VN-1.jpg', 1),
(4, 'https://cdn.tgdd.vn/Files/2021/09/17/1383447/dell-gaming-g15-phong-cach-thiet-ke-_1920x1080-800-resize.jpg', 2),
 
(5, 'https://www.notebookcheck.net/fileadmin/Notebooks/News/_nc4/Dell-XPS-13-9340-laptop.JPG', 1);

-- Thêm brand
INSERT INTO brands (brand_code, brand_name) VALUES
('DELL', 'Dell'),
('ASUS', 'Asus');

-- Thêm category
INSERT INTO categories (category_code, category_name) VALUES
('LAPTOP', 'Laptop'),
('ACCESSORY', 'Phụ kiện');

-- Thêm sản phẩm
INSERT INTO products (product_code, product_name, price, descriptions, brand_id, category_id, stock, rating)
VALUES
('P001', 'Dell XPS 13', 2500.00, 'Ultrabook cao cấp', 1, 1, 10, 4.5),
('P002', 'Asus ROG Strix', 2200.00, 'Laptop gaming', 2, 1, 5, 4.7);

-- Thêm account và client
INSERT INTO account (account_code, username, password_hash, roles)
VALUES
('ACC001', 'client1', crypt('password123', gen_salt('bf')), 'client'),
('ACC002', 'admin1', crypt('adminpass', gen_salt('bf')), 'admin');

INSERT INTO client (account_id, client_code, client_name, total_money)
VALUES
(1, 'CL001', 'Nguyen Van A', 0);

INSERT INTO admin (admin_id, account_id)
VALUES
(1, 2);
